### ISSUE TITLE
TBV not affecting prevalence or incidence

### ISSUE THREAD

**Issue by JDChallenger** [mrc-ide/malariasimulation#109]
Hi Giovanni,
I've run the vaccines vignette, implementation of the transmission-blocking vaccine isn't affecting prevalence or incidence of malaria in the population (easier to ascertain by increasing population size or turning off seasonality). The RTS,S vaccine seems fine. I'm not quite sure what's causing the issue, but the version of set_tbv() we were using last year contained the arguments 'start', 'end' & 'frequency', instead of 'timesteps'. So I wondered whether this is causing the issue. Happy to discuss in more detail if useful, and there's no huge rush to sort out. Thanks!

**Comment by giovannic** [comment]
Deffo! We should work out some parameters which present visible results!

We changed set_tbv so that we can vary converage over time.

Do we see any change by setting `prevalence_max_ages` and `prevalence_min_ages` to the vaccination ages? I wonder if the prevalence is looking at the wrong age group
