### ISSUE TITLE
Malariasimulation versions 1.3.0 does not have some parameters 

### ISSUE THREAD

**Issue by asiraj-nd** [mrc-ide/malariasimulation#166]
Having had malariasimulation 1.2.0 installed on my computer earlier, I installed malariasimulation package 1.3.0 on a second computer recently and noticed the new version does not have the parameter 'sever_enabled' (as well as a few other parameters including fvt, v). Any reason why I am getting 'unknown parameter' response?

**Comment by giovannic** [comment]
Hi @asiraj-nd, thanks for reaching out!

1.3.0 has a simpler severe Malaria model, which is closer to other models used at Imperial College. Please see this paper for details: https://pubmed.ncbi.nlm.nih.gov/25567652/

This new model will return severe incidence statistics as `n_inc_severe` if you set the `severe_incidence_rendering_min_ages` and `severe_incidence_rendering_max_ages` parameters.

We have removed prevalence parameters and outputs, since we do not yet have enough data on the duration of severe infection.

If you would like to estimate mortality statistics from the incidence data using your own values for fvt and v. I can recommend the method used by [P. Winskill et. al.](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002448) Supp. Materials 1, text F.

Please close this issue if your question is resolved, thanks!

**Comment by asiraj-nd** [comment]
Thanks @giovannic!
